PACKAGENAME=ZeroTier_VPN
MENUNAME="ZeroTier VPN"
VENDOR="Mo3he"
VERSION=BUILDVER
APPTYPE=native
APPNAME=ZeroTier_VPN
APPMAIN=ZeroTier_VPN
APPOPTS=""
OTHERFILES="lib html index.html"
SETTINGSPAGEFILE=index.html
LICENSE=
GRPNAME=
USERNAME=root
ARCHITECTURE=armv7hf
